apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      volumes:
        - name: service-cert
          hostPath:
           path: /usr/secrets
      containers:
        - name: httpserver
          image: quay.io/rh_ee_jcordoba/httpserver:0.5
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: service-cert
              readOnly: true
              mountPath: /usr/secrets
          env:
            - name: CERTIFICATE_FILE
              valueFrom:
                configMapKeyRef:
                  name: httpserver
                  key: CERTIFICATE_FILE
            - name: CERTIFICATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: httpserver
                  key: CERTIFICATE_KEY
