apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      volumes:
        - name: service-cert
          hostPath:
           path: /tmp
      containers:
        - name: httpserver
          image: quay.io/rh_ee_jcordoba/httpserver:0.3
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: service-cert
              readOnly: true
              mountPath: /tmp

