apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-httpserver
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpserver
                port:
                  number: 5000