apiVersion: v1
kind: Service
metadata:
  name: httpserver
spec:
  type: NodePort
  ports:
    - name: 8443-tcp
      protocol: TCP
      port: 5000
      targetPort: 8443
  selector:
    app: httpserver