name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: build-image
    - name: Build the Docker image
      env:
        DATE: $(date +%s)
      run: docker build . --file Dockerfile --tag httpserver:$DATE
    
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/rh_ee_jcordoba
        username: rh_ee_jcordoba
        password: ${{ secrets.REGISTRY_PASSWORD }}
